### ISSUE TITLE
Ninja & GMP

### ISSUE THREAD

**Issue by danielschemmel** [danielschemmel/fp-benchmarks-aachen#13]
The GMP test will not build with ninja. Since it does seem to build with make, further analysis is currently deferred.

**Comment by delcypher** [comment]
@danielschemmel I'm aware of this. For building GSL benchmarks we have a fix

https://github.com/delcypher/fp-benchmarks-imperial/blob/master/gsl/CMakeLists.txt#L38

I didn't include it in the code I contributed because I didn't want to pollute your code with support for a scenario I didn't think you'd use.

**Comment by danielschemmel** [comment]
Having pulled the block from @delcypher this should now work as of c7be00b3ffb9fb08624b33d6e992e0bb66e65486
